Add eslint and eslint plugin html
profusion/pf-website pull request #12
Opened 2021-04-13 19:01 UTC by GabrielBFurlani

2021-04-13 19:06 UTC, victor-accarini requested changes

2021-04-13 19:06 UTC, victor-accarini commented on package-lock.json
> +{
This file shouldn't exist... add to the .gitignore file

2021-04-13 19:06 UTC, victor-accarini commented on package.json
> +    "eslint-config-google": "^0.14.0",
This library is not necessary, if I'm not mistaken

2021-04-13 19:06 UTC, victor-accarini commented on package.json
> +    "eslint-plugin-html": "^6.1.2"
Should be a devDependency

2021-04-13 19:06 UTC, victor-accarini commented on .eslintrc.json
>      "rules": {
For the rules you can use some rules from the quickstart-graphql, leave this fix for last and call me so we can go trough which rules we will apply

2021-04-14 18:49 UTC, victor-accarini requested changes

2021-04-14 18:49 UTC, victor-accarini commented on package-lock.json
> +{
You also need to remove the file from the commit

2021-04-14 18:49 UTC, victor-accarini commented on .eslintrc.json
> +    "extends": ["eslint:recommended", "stylelint-config-standard", "plugin:css-modules/recommended"],
I would use the stylelint-config-recommended, since it doesn't have style rules, only bug related rules

2021-04-14 18:49 UTC, victor-accarini commented on .eslintrc.json
> +      "global-require": 0,
Change the zeros `0` with "off" and twos `2` with "error"

2021-04-14 19:18 UTC, cabelitos commented on .gitignore
> +package-lock.json
this can be removed from the ignore.

2021-04-15 13:01 UTC, victor-accarini approved these changes

2021-04-15 14:47 UTC, merged